version: '3.9'

services:
  web:
    depends_on:
      - db
    healthcheck:
      test: curl -s -f http://localhost:5000/healthcheck
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "5000:5000"
    networks:
      - web
    image: flask-app:latest
  db:
    image: ghcr.io/eslih/postgres:16.1-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - database

networks:
  web:
  database:
